Repository bsideup/liiklus, pull requests merged in 2019-07, with the labels that each got.

#127 support `null` keys
  app/src/main/java/com/github/bsideup/liiklus/service/ReactorLiiklusServiceImpl.java
  app/src/test/java/com/github/bsideup/liiklus/SmokeTest.java
  plugins/inmemory-records-storage/src/main/java/com/github/bsideup/liiklus/records/inmemory/InMemoryRecordsStorage.java
  tck/src/main/java/com/github/bsideup/liiklus/records/tests/SubscribeTest.java
Labels: bug

#129 add `GetEndOffsets` API
  api/src/main/java/com/github/bsideup/liiklus/records/FiniteRecordsStorage.java
  app/src/main/java/com/github/bsideup/liiklus/service/ReactorLiiklusServiceImpl.java
  app/src/test/java/com/github/bsideup/liiklus/EndOffsetsTest.java
  client/src/main/java/com/github/bsideup/liiklus/LiiklusClient.java
  client/src/main/java/com/github/bsideup/liiklus/RSocketLiiklusClient.java
  plugins/inmemory-records-storage/src/main/java/com/github/bsideup/liiklus/records/inmemory/InMemoryRecordsStorage.java
  plugins/kafka-records-storage/src/main/java/com/github/bsideup/liiklus/kafka/KafkaRecordsStorage.java
  protocol/src/main/proto/LiiklusService.proto
  tck/src/main/java/com/github/bsideup/liiklus/records/RecordStorageTests.java
  tck/src/main/java/com/github/bsideup/liiklus/records/tests/EndOffsetsTest.java
Labels: enhancement

#16 Add Apache Pulsar support
  plugins/pulsar-records-storage/build.gradle
  plugins/pulsar-records-storage/src/main/java/com/github/bsideup/liiklus/pulsar/PulsarRecordsStorage.java
  plugins/pulsar-records-storage/src/main/java/com/github/bsideup/liiklus/pulsar/config/PulsarRecordsStorageConfiguration.java
  plugins/pulsar-records-storage/src/test/java/com/github/bsideup/liiklus/pulsar/PulsarRecordsStorageTest.java
  tck/src/main/java/com/github/bsideup/liiklus/records/RecordStorageTestSupport.java
Labels: enhancement, plugin/pulsar

#134 use gRPC BOM
  build.gradle
Labels: dependencies, java

#135 Use Protobuf's BOM
  build.gradle
Labels: dependencies, java

#136 Update Gradle to 5.5
  api/build.gradle
  app/build.gradle
  client/build.gradle
  examples/java/build.gradle
  examples/plugin/build.gradle
  gradle/rerunTests.gradle
  gradle/wrapper/gradle-wrapper.properties
  plugins/dynamodb-positions-storage/build.gradle
  plugins/inmemory-positions-storage/build.gradle
  plugins/inmemory-records-storage/build.gradle
  plugins/kafka-records-storage/build.gradle
  plugins/pulsar-records-storage/build.gradle
  plugins/schema/build.gradle
  settings.gradle
  tck/build.gradle
  testing/build.gradle
Labels: dependencies

#143 Add grpc reflection service
  app/build.gradle
  app/src/main/java/com/github/bsideup/liiklus/config/GRPCConfiguration.java
Labels: enhancement

#142 #141 add redis backed positions storage
  plugins/redis-positions-storage/build.gradle
  plugins/redis-positions-storage/src/main/java/com/github/bsideup/liiklus/positions/redis/RedisPositionsStorage.java
  plugins/redis-positions-storage/src/main/java/com/github/bsideup/liiklus/positions/redis/config/RedisPositionsConfiguration.java
  plugins/redis-positions-storage/src/test/java/com/github/bsideup/liiklus/positions/redis/RedisPositionsStorageTest.java
  plugins/redis-positions-storage/src/test/java/com/github/bsideup/liiklus/positions/redis/config/RedisPositionsConfigurationTest.java
Labels: enhancement
